name: Publish Docker images

on:
  push:
    branches:
    - master
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* && git fetch --prune --unshallow
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Deploy
      run: mvn  -B -e -Dmaven.wagon.http.pool=false --settings settings.xml deploy
      env:
          GITHUB_USERNAME: harmanpa
          GITHUB_PASSWORD: ${{ secrets.GITHUB_ACCESS_TOKEN }}      
#    - name: Build and tag image 1
#      run: docker build --target worker -t "docker.pkg.github.com/$GITHUB_REPOSITORY/cauldron-worker:$(cat target/version.txt)" .
    - name: Build and tag image 2
      run: docker build --target cloudrun -t "docker.pkg.github.com/$GITHUB_REPOSITORY/cauldron-cloudrun-worker:$(cat target/version.txt)" .
    - name: Docker login
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
#    - name: Publish to GPR 1
#      run: docker push "docker.pkg.github.com/$GITHUB_REPOSITORY/cauldron-worker:$(cat target/version.txt)"
    - name: Publish to GPR 2
      run: docker push "docker.pkg.github.com/$GITHUB_REPOSITORY/cauldron-cloudrun-worker:$(cat target/version.txt)"
    - name: Deploy javadoc
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: target/site/apidocs/
        GH_PAT: ${{ secrets.GITHUB_ACCESS_TOKEN }}
    - name: Job Failed Notification
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2.1.2
      env:
        SLACK_CHANNEL: releases
        SLACK_COLOR: '#ff0000'
        SLACK_TITLE: 'Cauldron Build Failed'
        SLACK_USERNAME: cauldronbot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        MSG_MINIMAL: commit
        SLACK_FOOTER: CAE Tech
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.1.2
      env:
        SLACK_CHANNEL: releases
        SLACK_TITLE: 'New build of Cauldron'
        SLACK_USERNAME: cauldronbot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        MSG_MINIMAL: commit
        SLACK_FOOTER: CAE Tech
