name: Publish Docker images

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* && git fetch --prune --unshallow
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Deploy
      run: mvn  -B -e -Dmaven.wagon.http.pool=false --settings settings.xml deploy
      env:
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.GITHUB_ACCESS_TOKEN }}      

    - name: Build and tag image 1
      run: docker build --target worker -t "docker.pkg.github.com/$GITHUB_REPOSITORY/cauldron-worker:$(cat target/version.txt)" .

    - name: Build and tag image 2
      run: docker build --target cloudrun -t "docker.pkg.github.com/$GITHUB_REPOSITORY/cauldron-cloudrun-worker:$(cat target/version.txt)" .
      
    - name: Docker login
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
      env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Publish to GPR 1
      run: docker push "docker.pkg.github.com/$GITHUB_REPOSITORY/cauldron-worker:$(cat target/version.txt)"
      
    - name: Publish to GPR 2
      run: docker push "docker.pkg.github.com/$GITHUB_REPOSITORY/cauldron-cloudrun-worker:$(cat target/version.txt)"
